ALTER TABLE users ADD COLUMN IF NOT EXISTS username VARCHAR(100) NULL AFTER openId;

CREATE TABLE IF NOT EXISTS local_auth (
  open_id VARCHAR(64) NOT NULL PRIMARY KEY,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
